### ISSUE TITLE
Port Other than 443, Can It Be Configurable?

### ISSUE THREAD

**Issue by Imburr** [JOHLC/pfSense-FauxAPI-ha#15]
I have my firewall configured to use 4343 instead of 443 for security purposes (plus it conflict with web services behind it on that port. Try as I might I could not get this going with port 4343.

I tried:

switch:
  - platform: pfsense_fauxapi
    host: 192.168.2.1:4343
    api_key: !secret pf_key
    access_token: !secret pf_token
    rule_filter: ha

switch:
  - platform: pfsense_fauxapi
    host: 192.168.2.1
    port: 4343
    api_key: !secret pf_key
    access_token: !secret pf_token
    rule_filter: ha

switch:
  - platform: pfsense_fauxapi
    host: 192.168.2.1
    server_port: 4343
    api_key: !secret pf_key
    access_token: !secret pf_token
    rule_filter: ha

I also tried all combinations with:

pf_api_restart: "python3 /config/custom_components/pfsense_fauxapi/function-reboot.py 192.168.2.1:4343 PFFAXXX
pf_api_command: "python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.2.1:4343 PFFAXXX

These were the errors I got:

`
2021-06-24 20:11:53 ERROR (SyncWorker_3) [custom_components.pfsense_fauxapi.switch] Problem getting rule set from pfSense host: 192.168.2.1.  Likely due to API key or secret. More Info:HTTPSConnectionPool(host='192.168.2.1', port=443): Max retries exceeded with url: /fauxapi/v1/?action=config_get&__debug=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f864280ee20>: Failed to establish a new connection: [Errno 110] Operation timed out'))

2021-06-24 20:18:03 ERROR (SyncWorker_22) [homeassistant.components.command_line] Command failed: python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.2.1:4343 PFFAcredential1 3jmtdkbfvp3kndq5wswavbq4spakj6pmc82dno4sfc
Traceback (most recent call last):
  File "/config/custom_components/pfsense_fauxapi/function-iterate.py", line 26, in <module>
    gw_status = FauxapiLib.gateway_status()
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 95, in gateway_status
    return self._api_request('GET', 'gateway_status')
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 141, in _api_request
    raise PfsenseFauxapiException('Unable to complete {}() request'.format(action), json.loads(res.text))
PfsenseFauxapi.PfsenseFauxapiException: ('Unable to complete gateway_status() request', {'callid': '60d520bc375a2', 'message': 'action authorization failed'})
2021-06-24 20:18:04 ERROR (SyncWorker_24) [homeassistant.components.command_line] Command failed: python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.2.1:4343 PFFAcredential1 3jmtdkbfvp3kndq5wswavbq4spakj6pmc82dno4sfc
Traceback (most recent call last):
  File "/config/custom_components/pfsense_fauxapi/function-iterate.py", line 26, in <module>
    gw_status = FauxapiLib.gateway_status()
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 95, in gateway_status
    return self._api_request('GET', 'gateway_status')
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 141, in _api_request
    raise PfsenseFauxapiException('Unable to complete {}() request'.format(action), json.loads(res.text))
PfsenseFauxapi.PfsenseFauxapiException: ('Unable to complete gateway_status() request', {'callid': '60d520bc3d358', 'message': 'action authorization failed'})
2021-06-24 20:18:04 ERROR (SyncWorker_16) [homeassistant.components.command_line] Command failed: python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.2.1:4343 PFFAcredential1 3jmtdkbfvp3kndq5wswavbq4spakj6pmc82dno4sfc
Traceback (most recent call last):
  File "/config/custom_components/pfsense_fauxapi/function-iterate.py", line 26, in <module>
    gw_status = FauxapiLib.gateway_status()
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 95, in gateway_status
    return self._api_request('GET', 'gateway_status')
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 141, in _api_request
    raise PfsenseFauxapiException('Unable to complete {}() request'.format(action), json.loads(res.text))
PfsenseFauxapi.PfsenseFauxapiException: ('Unable to complete gateway_status() request', {'callid': '60d520bcf0495', 'message': 'action authorization failed'})
2021-06-24 20:18:05 ERROR (SyncWorker_24) [homeassistant.components.command_line] Command failed: python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.2.1:4343 PFFAcredential1 3jmtdkbfvp3kndq5wswavbq4spakj6pmc82dno4sfc
Traceback (most recent call last):
  File "/config/custom_components/pfsense_fauxapi/function-iterate.py", line 26, in <module>
    gw_status = FauxapiLib.gateway_status()
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 95, in gateway_status
    return self._api_request('GET', 'gateway_status')
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 141, in _api_request
    raise PfsenseFauxapiException('Unable to complete {}() request'.format(action), json.loads(res.text))
PfsenseFauxapi.PfsenseFauxapiException: ('Unable to complete gateway_status() request', {'callid': '60d520bd02736', 'message': 'action authorization failed'})
2021-06-24 20:18:05 ERROR (SyncWorker_13) [homeassistant.components.command_line] Command failed: python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.2.1:4343 PFFAcredential1 3jmtdkbfvp3kndq5wswavbq4spakj6pmc82dno4sfc
Traceback (most recent call last):
  File "/config/custom_components/pfsense_fauxapi/function-iterate.py", line 26, in <module>
    gw_status = FauxapiLib.gateway_status()
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 95, in gateway_status
    return self._api_request('GET', 'gateway_status')
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 141, in _api_request
    raise PfsenseFauxapiException('Unable to complete {}() request'.format(action), json.loads(res.text))
PfsenseFauxapi.PfsenseFauxapiException: ('Unable to complete gateway_status() request', {'callid': '60d520bdae6bd', 'message': 'action authorization failed'})
2021-06-24 20:18:05 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed: python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.2.1:4343 PFFAcredential1 3jmtdkbfvp3kndq5wswavbq4spakj6pmc82dno4sfc

2021-06-24 20:19:11 ERROR (SyncWorker_6) [custom_components.pfsense_fauxapi.switch] Problem getting rule set from pfSense host: 192.168.2.1.  Likely due to API key or secret. More Info:HTTPSConnectionPool(host='192.168.2.1', port=443): Max retries exceeded with url: /fauxapi/v1/?action=config_get&__debug=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb73b382460>: Failed to establish a new connection: [Errno 110] Operation timed out'))
`

**Comment by JOHLC** [comment]
First and foremost I hope that:
```PFFAcredential1 3jmtdkbfvp3kndq5wswavbq4spakj6pmc82dno4sfc```
Isn't actually your credential. If it is, I suggest you change it

Next, I am not sure if this is possible - at least I haven't tested. 
This should not interfere with other hosts running on port 443 as you are pointing it explicitly at the pfsense router correct? 
I think even if you were using pfsense as a reverse proxy, this could work because fauxapi uses the base url: fauxapi/v1

How do you have a different port for your fauxapi instance configured?

**Comment by Imburr** [comment]
Not my credentials, I am pointing it explicitly at the router, yep. I am not configuring a differed port for fauxapi... and I did change my pfsense box to work off of 443 and the issues continue in the same manner.

I will keep plugging away, thanks for the fast response!

**Comment by JOHLC** [comment]
Reference: https://github.com/ndejong/pfsense_fauxapi/issues/48

Good news, give me a few. Would you be willing to beta test?

**Comment by Imburr** [comment]
Sure!

I think the reason might be my FauxAPI install on the pfSense.

![image](https://user-images.githubusercontent.com/2759346/123353086-b9f53980-d52e-11eb-8167-56b6e653dd59.png)

![image](https://user-images.githubusercontent.com/2759346/123353095-c2e60b00-d52e-11eb-93f3-0d803c093491.png)

Looks like my python on pfsense is missing, I swear I installed it.

**Comment by JOHLC** [comment]
I don't think (although this is an uninformed thought) that fauxAPI needs to have python on your pfsense box does it?
Do you use fauxapi for anything else or were you just trying to get it setup for Home Assistant?

**Comment by Imburr** [comment]
I do not need Python on pfsense, you are right. Looks like client libraries were not installed in HA, or only partially installed. I deployed again, but still the same problems.

2021-06-24 21:11:27 ERROR (SyncWorker_6) [homeassistant.components.command_line] Command failed: python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.2.1 PFFA* *
Traceback (most recent call last):
  File "/config/custom_components/pfsense_fauxapi/function-iterate.py", line 27, in <module>
    int_status = FauxapiLib.interface_stats(interface)
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 92, in interface_stats
    return self._api_request('GET', 'interface_stats', params={'interface': interface})
  File "/config/custom_components/pfsense_fauxapi/PfsenseFauxapi.py", line 141, in _api_request
    raise PfsenseFauxapiException('Unable to complete {}() request'.format(action), json.loads(res.text))
PfsenseFauxapi.PfsenseFauxapiException: ('Unable to complete interface_stats() request', {'callid': '60d52d3fd6582', 'message': 'action authorization failed'})
2021-06-24 21:11:27 ERROR (SyncWorker_1) [homeassistant.components.command_line] Command failed: python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.2.1 PFFA* *

Same error logs in pfsense as well. I feel like there is something obvious I am missing...

**Comment by JOHLC** [comment]
are you certain your cerdentials.ini file is configured correctly and you aren't using the example credentials? 
Also just to confirm, you are now on port 443 with https enabled on pfsense?

**Comment by Imburr** [comment]
Yeah I am now on 443, yes sir.

Maybe my credentials are borked, here they are (I have changed them).

[PFFAcredential2]
secret = y48a76ttwyn7sq5paobscdxofimmc2kz4enssqroij
permit = alias_*, config_*, gateway_*, rule_*, send_*, system_*, function_*
comment = This is my API credential to allow HASS to access pfSense API through FauxAPI.

**Comment by Imburr** [comment]
I used the script to generate new creds, and they still fail:

2021-06-24 21:24:17 ERROR (SyncWorker_11) [homeassistant.components.command_line] Command failed: python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.2.1 PFFX 1234

**Comment by Imburr** [comment]
I am using a wildcard certificate, if that matters any.

**Comment by JOHLC** [comment]
try: permit = *  
?

**Comment by Imburr** [comment]
Pertmi * worked. I re added interface_* into the credential again and it is now working: 
alias_*
config_*
gateway_*
rule_*
send_*
system_*
function_*
interface_*

Still some items not updating, but at least I am getting something, and I can work through those. Thanks for all of your help!

**Comment by JOHLC** [comment]
https://github.com/JOHLC/pfSense-FauxAPI-ha/releases/tag/202106.1-dev1
![image](https://user-images.githubusercontent.com/63735432/123358194-0cd3ee80-d539-11eb-877c-c9b2fe66fa6d.png)

Check out this beta release and see if it works for you with a different port configured for pfsense? I am not getting any errors but I am using 443 still. 


for configuration, setup your switch platform like this (note the port field): 
````
  - platform: pfsense_fauxapi
    host: 192.168.2.1
    port: 443 #Or whatever
    api_key: !secret pf_key
    access_token: !secret pf_token
    rule_filter: ha

````


For your secrets.yaml - note the second argument is now the port number you have setup with pfsense:
````
pf_api_restart: "python3 /config/custom_components/pfsense_fauxapi/function-reboot.py 192.168.2.1 443 PFFAwhatever yourlongtoken"

pf_api_command: "python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.2.1 443 PFFAwhatever yourlongtoken"

pf_key: PFFAwhatever
pf_token: yourlongtoken

````

**Comment by MatthewGCampbell** [comment]
Found this issue, was testing it with 8443, and it didn't seem to work, is their a way to change the port the Faux api listens on, because I think that might be my issue, everything works fine on 443, but thats my web gui, don't really want to allow access to that, and I don't want to change my web gui port.

**Comment by JOHLC** [comment]
> Found this issue, was testing it with 8443, and it didn't seem to work, is their a way to change the port the Faux api listens on, because I think that might be my issue, everything works fine on 443, but thats my web gui, don't really want to allow access to that, and I don't want to change my web gui port.
> 
> edit: the Faux API seems to bind to the web gui port, as when I switched the web gui port it no longer worked on 443, and when I switched it back it worked, without touching my home assistant config.

Yea, my understanding is that it binds to whatever web gui port you are using. 

Were you able to test with the beta version and a different webgui port specified?

**Comment by MatthewGCampbell** [comment]
> > Found this issue, was testing it with 8443, and it didn't seem to work, is their a way to change the port the Faux api listens on, because I think that might be my issue, everything works fine on 443, but thats my web gui, don't really want to allow access to that, and I don't want to change my web gui port.
> > edit: the Faux API seems to bind to the web gui port, as when I switched the web gui port it no longer worked on 443, and when I switched it back it worked, without touching my home assistant config.
> 
> Yea, my understanding is that it binds to whatever web gui port you are using.
> 
> Were you able to test with the beta version and a different webgui port specified?

Yeah beta works flawlessly, but it always has to be on the specified gui port, not sure if its possible to separate the port from the web gui.

**Comment by JOHLC** [comment]
Ref: https://github.com/ndejong/pfsense_fauxapi/issues/48#issuecomment-497995906

There's currently no way to specify a listening port other than the web gui port it seems

**Comment by Imburr** [comment]
Confirmed this works. My web GUI port is 4343, and FauxAPI works with the above port configuration settings. I use 443 inside for a different application with NAT and rules, so this works great.
